const firstNames=["Alex","Avery","Casey","Charlie","Drew","Emery","Harper","Jamie","Jordan","Morgan","Quinn","Riley","Rowan","Sam","Taylor"];
const lastNames=["Anderson","Bennett","Brooks","Campbell","Carter","Collins","Davis","Ellis","Foster","Garcia","Hayes","Kim","Martin","Nguyen","Parker","Patel","Reed","Rivera","Taylor","Walker"];
const domains=["example.com","mailtest.dev","sample.org"],streets=["Maple Avenue","Cedar Lane","Willow Street","Lakeview Drive","Parkside Road","Juniper Way"],cities=["Portland","Austin","Madison","Denver","Raleigh","Boulder"],companies=["Northstar Labs","Pine & Pixel","Brightline Studio","Cobalt Systems","Daybreak Co.","Horizon Works"];
const $=id=>document.getElementById(id);let sequence=0;const random=max=>crypto.getRandomValues(new Uint32Array(1))[0]%max;const pick=items=>items[random(items.length)];
const themes={system:{label:"System",icon:"◐"},dark:{label:"Dark",icon:"☾"},light:{label:"Day",icon:"☀"}};
let themeAnimationTimer;
let foxGlowTimer;
function triggerFoxGlow(){const logo=document.querySelector(".logo");logo.classList.remove("fox-glow");void logo.offsetWidth;logo.classList.add("fox-glow");clearTimeout(foxGlowTimer);foxGlowTimer=setTimeout(()=>logo.classList.remove("fox-glow"),650)}
function animateThemeShift(){const app=document.querySelector(".app");app.classList.remove("theme-shift");void app.offsetWidth;app.classList.add("theme-shift");triggerFoxGlow();clearTimeout(themeAnimationTimer);themeAnimationTimer=setTimeout(()=>app.classList.remove("theme-shift"),560)}
function setTheme(theme,animate=false){document.documentElement.dataset.theme=theme;$("theme-label").textContent=themes[theme].label;$("theme-icon").textContent=themes[theme].icon;localStorage.setItem("fake-data-filler-theme",theme);if(animate){const button=$("theme-toggle");button.classList.remove("pop");void button.offsetWidth;button.classList.add("pop");setTimeout(()=>button.classList.remove("pop"),520);animateThemeShift()}}
function generate(){const firstName=pick(firstNames),lastName=pick(lastNames),digits=()=>String(random(900)+100),alphabet="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";return{firstName,lastName,name:`${firstName} ${lastName}`,username:`${firstName.toLowerCase()}${lastName.toLowerCase()}${random(999)}`,email:`${firstName}.${lastName}${random(99)}@${pick(domains)}`.toLowerCase(),phone:`+1 (${digits()}) ${digits()}-${String(random(10000)).padStart(4,"0")}`,password:Array.from({length:16},()=>alphabet[random(alphabet.length)]).join(""),company:pick(companies),address:`${random(8999)+100} ${pick(streets)}`,city:pick(cities),state:"CA",zip:String(random(90000)+10000),country:"United States",website:"https://example.com",bio:"Testing a form with generated placeholder content."}}
let profile=generate();function render(message="Ready when you are."){["name","email","phone","password","company","address","city","zip"].forEach(key=>$(key).textContent=profile[key]);$("identity-number").textContent=String(++sequence).padStart(3,"0");$("status").className="status";$("status").textContent=message}
async function copyValue(key,button){try{await navigator.clipboard.writeText(profile[key]);button.querySelector("i").textContent="✓";setTimeout(()=>button.querySelector("i").textContent="⧉",1000)}catch(_){$("status").className="status error";$("status").textContent="Couldn’t copy that value."}}
async function fillActiveTab(profile,groups){const[tab]=await chrome.tabs.query({active:true,currentWindow:true});try{return await chrome.tabs.sendMessage(tab.id,{type:"FILL_FAKE_DATA",profile,groups})}catch(_){await chrome.scripting.executeScript({target:{tabId:tab.id},files:["content.js"]});const[result]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:(generatedProfile,selectedGroups)=>globalThis.__fakeDataFiller?.(generatedProfile,selectedGroups)||{filled:0},args:[profile,groups]});return result.result}}
document.querySelectorAll(".copy-item").forEach(button=>button.addEventListener("click",()=>copyValue(button.dataset.copy,button)));
$("regenerate").addEventListener("click",()=>{const button=$("regenerate"),app=document.querySelector(".app");button.classList.remove("refreshing");app.classList.remove("refreshing-data");void button.offsetWidth;button.classList.add("refreshing");app.classList.add("refreshing-data");triggerFoxGlow();setTimeout(()=>{button.classList.remove("refreshing");app.classList.remove("refreshing-data")},580);profile=generate();render("Fresh identity generated.")});
$("theme-toggle").addEventListener("click",()=>{const order=["system","dark","light"],current=document.documentElement.dataset.theme,next=order[(order.indexOf(current)+1)%order.length];setTheme(next,true)});
window.matchMedia("(prefers-color-scheme: light)").addEventListener("change",()=>{if(document.documentElement.dataset.theme==="system")animateThemeShift()});
$("toggle-all").addEventListener("click",()=>{const boxes=[...document.querySelectorAll(".chips input")],selectAll=boxes.some(box=>!box.checked);boxes.forEach(box=>box.checked=selectAll);$("toggle-all").textContent=selectAll?"Clear all":"All fields"});
$("fill").addEventListener("click",async()=>{const button=$("fill"),groups=[...document.querySelectorAll(".chips input:checked")].map(box=>box.value);if(!groups.length){$("status").className="status error";$("status").textContent="Choose at least one type of field.";return}button.disabled=true;$("status").className="status";$("status").textContent="Finding matching fields…";try{const result=await fillActiveTab(profile,groups),count=result?.filled||0;$("status").className=`status ${count?"success":"error"}`;$("status").textContent=count?`Filled ${count} field${count===1?"":"s"} — nice and tidy.`:"No matching fields found here."}catch(_){$("status").className="status error";$("status").textContent="Chrome can’t fill this page."}finally{button.disabled=false}});setTheme(localStorage.getItem("fake-data-filler-theme")||"system");render();
